[workspace]

members = [
    "treeedb",
    "treeedb-c",
    "treeedb-java",
    "treeedb-souffle",
    "treeedbgen",
    "treeedbgen-souffle",
    "treeedbgen-souffle-c",
    "treeedbgen-souffle-java",
    "treeedbgen-souffle-souffle",
]

[profile.release]
lto = "thin"
