[package]
name = "treeedbgen"
version = "0.1.0"
edition = "2021"
description = "Parse node-types.json from a tree-sitter grammar"
keywords = ["parsing", "tree-sitter"]
authors = ["Langston Barrett <langston.barrett@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/langston-barrett/treeedb"
repository = "https://github.com/langston-barrett/treeedb"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"