on:
  push:
    tags:
    - 'v*'

name: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run Datalog generators
      run: |
        cargo run --bin treeedbgen-souffle-java -- --output treeedb-java.dl --prefix java
        cargo run --bin treeedbgen-souffle-souffle -- --output treeedb-souffle.dl --prefix dl

    - name: Deps
      run: |
        sudo apt-get install -y musl-tools
        rustup target add x86_64-unknown-linux-musl

    - name: Build static executables
      run: |
        make static
        mkdir exe/
        cp target/x86_64-unknown-linux-musl/release/treeedb-java exe/
        cp target/x86_64-unknown-linux-musl/release/treeedb-souffle exe/

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "exe/treeedb-java,treeedb-java.dl,exe/treeedb-souffle,treeedb-souffle.dl"
        artifactErrorsFailBuild: true
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
